name: cpd-backflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - jax==0.4.34
    - jaxlib==0.4.34
    - mpi4jax==0.5.4
    - mpi4py==4.0.1
    - netket[mpi]==3.14.3
    - pyscf==2.5.0
    - ml-collections
    - git+https://github.com/BoothGroup/GPSKet.git#egg=GPSKet
